version: '3'

services:

  nginx-api-demo:
    image: nginx:1.19.8-alpine
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./script:/etc/nginx/script